dist: trusty
sudo: false
language: node_js
node_js:
- '9'
os:
- linux
cache: yarn
env:
  global: 
    - # Environment variables for NPM version patch    
    - secure: "JQD1W4JV5nuPtaBXCskwmZ5jKcuL+yOzLw2LZYEYjc7Ick/0gHoOftV7v9HLclBBiX7e/QlKrBIfsx77VdFDWlg29hMtdgwLlIrgK4D6SN9ixI/RpjDBXBPic8G1mck3B8wE2/HRqo3gU8QNJCrXmFqADq9BbMnX1BWGQEn/IiK89lyA1Ad85gm1wnB55mM39DrBR6eO1sUiFxPmzez8eUkpvl5tLnDuMROhCt/RASphzcE5PNOMrsFz3CyVUkv0ZkFMRRTjSnrIaDlLYlVIkGEHDljX7nhbTDtaBQQLskcuwXHE0aiXiCL5uRResVAvHVbF9zLfnx7mbmvMkvakKa97vSsCV/CoyTrQDgbvjtvmuMhVzuJhy9MUUnD+28Mzq+vyvb9DIhRmrrqb6pis5ooHZU3k11ZEBeVsLj+Y74UqOlo1ZkYXbEcXZveeaNrBBF0oEDQdT3XwDyDb4I/1bNUIhQJ6pPTDzFXRQeJPbRpYrtT97xUBoY2KVhOZnW1TkKBO9VBHL3TFGxPASkJNzLb6RU4f15WkZ8xyPhXUwRLIca/fcYGIXkNV0SiOEoMcUfaKeKhk4gqPIEOWut7GaQSARAj09NFysoXpbCLKbynuDUUJm6zJNHFhiMmUMwwv11ESFjbPQRmswG0O/InUpTZdHUxt8bykIw3e3bfYQDs="
    - secure: "hvlzYK1EnQJsy7CR+eFvHoaFPNimO4eZ1Vj4wnB26ZEjspVavNtuTtFM4Dpk4ZqiWwSAwfPKG7WOM3pHgblcmEIm24HggIj5AWHrG/5D957LuiuCCil0euqzjJbbiVWY6sFjPr7b5I3/5jehkqpoLmHC008TVXFmLMqgIMYVna/jO9PT/NyAKM1NeNXVFF6z79aGqQktP5NYT0KPI89Onhc8O+yzzcMwu73Nmxh1wc1ZasVJhkx5WV1iVEnnenAnQz7MaGnAejl7sgLAfW0Qu3LrG6VzN5FAcvlZaS7qamoq9fB3xeLs+8peA2GyLNN6ePrbR+T9BbdV0TvyX6AIyobE7qZxDX9JBfUTBcp3SjUM6JbD2tWZYubjjBbvPBhUO+u7bz/yb8RYNbYxlW9mIPR6vgv27vCD6tDVRcmhm56ZW4ppxuZ1DSsaczv4hJNd+u4lYp0ImjPAVrdU96+myZWy5z5PzMLqknhi0UyLmzvRHWlMH9Ikc8kFg8Q/+y58mmo/S0MIhRj1So2iMhthik3x1CLkaB27sIyoVHAnFUSg3OQxEuqTvxxaccSqipvosiKz6ltwjr7IPuc5VG4GwZOufhJKcmGxxutFdEej5GedDHEWGDmKn9l7h3WwKk2hm/GCI/es4Az5BViNaQcfxua52SIFfHvG0MZ8gXdOZDQ=" 

  matrix:
    - FIREFOX_VERSION="latest"
    - FIREFOX_VERSION="61.0.2"
before_install:
- echo $FIREFOX_VERSION
- export FIREFOX_SOURCE_URL='https://download.mozilla.org/?product=firefox-'$FIREFOX_VERSION'&lang=en-US&os=linux64'
- wget --no-verbose -O /tmp/firefox-$FIREFOX_VERSION.tar.bz2 $FIREFOX_SOURCE_URL
- mkdir /tmp/firefox-$FIREFOX_VERSION
- tar -xvf /tmp/firefox-$FIREFOX_VERSION.tar.bz2 -C /tmp/firefox-$FIREFOX_VERSION
- export PATH=/tmp/firefox-$FIREFOX_VERSION/firefox:$PATH
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- export CHROME_BIN=/usr/bin/google-chrome
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
- export PATH="$HOME/.yarn/bin:$PATH"
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation google-chrome-stable
install:
- yarn install
script:
- firefox --version
- npm run lint
- npm run test:once
- npm run e2e
after_success:
- npm run packagr
# Autoincrement of patch level version:
# Tag the repo with a new patch level version tag, if this build is done on
#     'FIREFOX_VERSION = latest' and (only one of the matrix-builds is relevant)
#     this is not a pull request and (pull requests themselves should not autoincrement)
#     this branch is the master branch and (only builds on master are relevant)
#     there is no tag given (if a tag is alread given, this one will be published and should not again be tagged!)
- 'if [ "$FIREFOX_VERSION" = "latest" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_TAG" = "" ]; then wget https://github.com/test-editor/commons-build-automation/raw/master/travis/deploy/tag_with_new_patch_version.sh; bash tag_with_new_patch_version.sh; fi'
before_deploy:
- touch .npmignore
- cd dist/
deploy:
  skip_cleanup: true
  provider: npm
  email: service.eng@akquinet.de
  api_key:
    secure: "OzXlE96xucTDwBjB9pxTJ5CPOEm2elr6hIMh7GRsK4kJPD9qekfyTJ5SS4akwZv1021MGRhpIPIyE0pyD5KWwGIBjvHERq3G72BuJDo9NgNghSCwSfYR/HJ9SR8ld19NlMZuTRwuosIv5aF+R5THgLvbEMgYz3k8WsPpzPzS2e0pjqcYH6uiPF5UsBJto7IeyXTSXeX+cx92IHgEBY0/SrGF9te7avBl7ZMdtRrFaQaxbpW0qnZyI7v2fnCflHPMbcPKAHWNcWlx1LmK3HeEy6tI7F+Ltk9+xzVv/Nwd8ARrdgc7fV4YnedJVIXJUK2dDZTiPkdBBrMG5WJYHaZSM5kc/5KZOy6Bb+8+9/gx1oHMcz/PEGVxmIzxiBw3oBfkBorompUzw149n/j0UDZi76MgVXIHT9HSvQ0Thu0eddtN+ggvUuH9apQ0VOZ+43xn5ENaa8xX6HQsNEfkakpQx5bdOm/v/GoaXrntrB9Uef2yXZvyVXTBOsng2+/UM/Ok529O+Cy3cBXiQu7Gk//fmUCmEQKFLp0kK6fnuHnzp9vzxZfWO6uu9Woq2yThMD/8LvV5StZzH19nV7PNgFyuhgLiILRwPpu3BQAvfP59QbWCugQTcVhfIXUkFQFNrzupeFncLnedD6HeXPhHdgJ77LEkl7qhSp9Lo8zJAD8vvD0="
  on:
    condition: "$FIREFOX_VERSION = latest"
    tags: true
    repo: test-editor/web-teststep-selector
