language: nix
sudo: false
cache:
  directories:
  - "$HOME/nix.store"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- sudo mkdir -p /etc/nix
# make sure no browser is left over that can disturb the karma tests (nix-shell provides the browsers!)
- sudo apt-get remove google-chrome-stable -y
- sudo apt-get remove chromium-browser -y
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs

env:
  global:
    - # GitHub Environment variables for NPM version patch
    - secure: "ixDj4L+7/yPRcUi5U0UfawI0cx18cXP2Xho5epa0rufzAriafphB3YCvKrlmjxnGLCGOGgGVQDeZ4W2wCAysS2+CD6LtbZlnKVN+dWZHYMbgBDecHSq9TAdcMLBtQBch50nFHhkybOg1rQU/AyZJNIl5uuG+QXbShLZ3NKoFsVd9PuM5JKSkZu+XgUnuyR+WspchtW5tTZwdcUA4go3jR8aIYvx7nL+Ggq/Tjp+Ox7+82YeAnb/OQAlsSWo1Le6QQCSRqvyiN+VTlQ2RHlrcSV0o3CLBAAFE7a6BJqiUva7VZwJhMs1dNyn+zZPoCC75X8mnwnsI/q1Bxn7h/7GFvcJ+h7FrLwIk0R8Kgx0UBXIooGrxcYDFvNb3F3aeEvbmpGoWXgySCronacPLr8Nh13SCLw6OK8jljz22/z9iuA6HiYtC25w53NgJCju/yWdLjMbWQgegGV4+PDw5AEB/CM5CiBjUrJSL4Klf6qWVEJUrkynLSKmQxVdZXW9Isj2YugtRySSCT/EImWdV4Z+DoAjwxMTNFkORlmR4cWZUfJKd93RqGC2bOUpL2E0RbHsDBXpqcipOEZ+MRomLz7W/23tZDvoYBHnv2dxizqRAksvFCyrLg86ZxbdET4GDiylg85i33OuljcUkZrDXeO5ujvAP555oQrptQXUsMlEIJX4="
    - secure: "UToiI36n8HV8EcA2ITFyxtXWilbhTWdYRVp6j64bbYZyzsQZCWUUZByXMoYHmHHZqinxN4UenyTnx5aoiFKkWCArqhejX8t3cIQVCh1AtaZZ/znF9eaKfqQCFoADMbSa0H5dhbmUxOoQwEJ/kGz48QwIybuZCQJRpdib+4oMverdBVNoWMAFZdse9TyZQdAk/3hx8f47LS0W3L2WKzCSJEgQbmvieCRoPO4rbZ2PVeGlbZWi6GgBtcry6WT2OPV/UhqkUwGj5R0csYbNan71jQngkTUdxi2o5aa2VYoolrGvvY3KHY6I/8e1WlVIl71nvj7soiT/adfQE9y2FE+jZBSf41ITW+mRH7Ch2d6X0w1lxHKGdR9a3Dx0xVQU9zp4NlFB5B6d6q4QARvNFLObhhstQwKZoVYvT8Go2UffcSSi7t7kpbP52PXwKuBfRomvHZ2BG+v6dL9o+lFvJjqBdusS1+GyUUEV43UtHzvB9/2LQ0p6ZmvdySuG8Azept7TrkvrqOiNccUJ3CLgrRrLTXTBgB/Qbp4Rex4puPxLUuShFrG2wB+ceD0+dYgZnaTjj2qrQtu7Iqt/hyoCAcd4sIaaAJrBjWCf/HGiZ7cOWpulp73MqARKqILT+ugWwz+FczOPwJ2Xxi+DrZWgza1tGFgNnAEO2NQf25p1rBIKXOk="
    - NIXPKGS_ALLOW_UNFREE: 1

  matrix:
    - FIREFOX_VERSION="latest"
    - FIREFOX_VERSION="60-esr"

install:
- nix-shell shell-${FIREFOX_VERSION}.nix --command "yarn install"
script:
- nix-shell shell-${FIREFOX_VERSION}.nix --command "firefox --version"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "google-chrome --version"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "yarn run lint"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "xvfb-run --server-args=\"-ac -screen 0 1920x1080x16\" yarn run test:once"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "xvfb-run --server-args=\"-ac -screen 0 1920x1080x16\" yarn run e2e"

after_success:
- nix-shell shell-${FIREFOX_VERSION}.nix --command "yarn run packagr"
# Autoincrement of patch level version:
# Tag the repo with a new patch level version tag, if this build is done on
#     'FIREFOX_VERSION = latest' and (only one of the matrix-builds is relevant)
#     this is not a pull request and (pull requests themselves should not autoincrement)
#     this branch is the master branch and (only builds on master are relevant)
#     there is no tag given (if a tag is alread given, this one will be published and should not again be tagged!)
- 'if [ "$FIREFOX_VERSION" = "latest" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_TAG" = "" ]; then wget https://github.com/test-editor/commons-build-automation/raw/master/travis/deploy/tag_with_new_patch_version.sh; nix-shell shell-${FIREFOX_VERSION}.nix --command  "bash tag_with_new_patch_version.sh"; fi'
before_deploy:
- touch .npmignore
- cd dist/
deploy:
  skip_cleanup: true
  provider: npm
  email: testeditor.eng@gmail.com
  api_key:
    secure: "u2i2pJHXDrspfwXohLUYfZkXrhMpUXaWiBy7ir1AbzYsgFk8+0cTRu6U3UtcsfVq545mNN1hwHmTKpr7S1AWA9DMFn4Q5roXUqjqH7L0m2RNfWT4Ru0yRm4aXdLOGlxhODZQi5TRq3ak7OGpupx2RdX5ukWfD+P++//8jgerPN6arZkwQmi3OSXU5eUHWTQXoSeLnfCxWmxdZn0B+KuT+nUXrhwVuUiQ8ENn/4inaCsfIOY6X+8TjK5jF+w3z+9GwMrIaDIgZwCJaCXQ99PnAMX1SxDhrwCsePrxM0VCeODM58QIMM5N5n836HIVJi4hXcuNFSpP9eKpE8pwe2jr4N8i3PQGS/01N+ZtXC/28rFulDDmx9HwEZVhTZWy+Tvc8c/eio0H41DkPrCQD7NcB1craml3z8hXcHfcvJx5daQIAlCERvfan+C+lROA1bPnqDLfH0q9sLLktyRnrtGt4hnnxlrKbsBYT2HPMsnP3+1lprioKjzNbet5qRgc70ubj2Dakgvb+Z1ifSP3K2f3/j1AfVy3upVItyA46FCKkAi73aV7FzWWk7ha640DXeaCASbb3KujIomJI9a/w7Gj5WGOhw5w7Dz8n/6VXA+1Kh92BobwHukIpojqH/Er7Dw4mmUd6/Sn5AbFIQWPzRVFFB0niZIf6lgl1lQWjeXd4oQ="
  on:
    condition: "$FIREFOX_VERSION = latest"
    tags: true
    repo: test-editor/web-teststep-selector
